# Generated by Django 2.0.13 on 2019-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_password', models.IntegerField()),
                ('UUID', models.CharField(max_length=255)),
                ('ho', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=40)),
                ('identification', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'apartment',
            },
        ),
    ]
